config/routes.rb
MyBlog::Application.routes.draw do
  resources :sessions, only: [:create,:destroy,:new]
  resource :contacts, only: [:create]
  resources :posts do
    resources :comments, only: [:create,:destroy]    
  end

  root to: "posts#index"

  delete '/salir', to: 'sessions#destroy'
  match 'entrar', to: "sessions#new"

  match '/mensajes', to: "users#mensajes"
  put '/leido/:id', to: 'comments#leido', as: "comment_leido"
  get '/:title', to: "posts#show", as: 'post_title'

  

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  email      :string(255)
#  name       :string(255)
#  content    :text
#  post_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  leido      :boolean          default(FALSE)
#

class Comment < ActiveRecord::Base
  attr_accessible :content, :email, :name, :post_id, :leido
  belongs_to :post, :class_name => "Post", :foreign_key => "post_id"
  after_save :enviar_email_creado
  #before_destroy :enviar_email_destruido
  FORMAT_EMAIL = /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i
  validates :content, :email, :name, presence: true
  validates :email, format: {with: FORMAT_EMAIL}


	private
	  def enviar_email_creado
	  	Usermail.delay.comentario_creado(self)#.deliver
	  end

	  def enviar_email_destruido	  	
	  	Usermail.delay.borrar_comentario(name,email,content)#.deliver	  	
	  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :email, :msg, :name
  after_save :enviarme_mensage
  FORMAT_EMAIL = /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i

  validates :email, :msg, :name, presence: true
  validates :email, format: {with: FORMAT_EMAIL}
	def enviarme_mensage
		Contactmail.delay.enviar_email(self)		
	end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  content    :text
#  title      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Post < ActiveRecord::Base
  attr_accessible :content, :title 
  has_many :comments, dependent: :destroy
  belongs_to :user, :class_name => "User", :foreign_key => "user_id"
  
  scope :previo, lambda { |id| where("id < ?", id).order('id DESC').limit(1) }
  scope :siguiente, lambda { |id| where("id > ?", id).limit(1) } 
  scope :ultimos_post, where('id <= ?', Post.last).order('id DESC').limit(5)
  def self.otros(id)
    [previo(id),siguiente(id)]
  end  

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(255)
#  name            :string(255)
#  password_digest :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password_digest, :password, :password_confirmation
  has_secure_password
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_filter :ultimo, :mensajes_nuevos, :contact_builder
  protect_from_forgery
  include ApplicationHelper

  def mensajes_nuevos
  	@noleidos = Comment.where('leido = ?',false)
  end
  def ultimo  	
  	@ultimos = Post.ultimos_post
  end

  def contact_builder
  	@contact = Contact.new
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.build(params[:comment])		
		if @post && @comment.save			
			redirect_to post_title_path(@post.title), notice: "Comentario creado"			
		else
			flash[:error] = "Comentario Invalido"
			redirect_to post_title_path(@post.title)		
		end			
	end

	def destroy		
		post = Post.find(params[:post_id])
		comment = post.comments.find(params[:id])		
		comment.destroy
		@id = params[:id]
		respond_to do |wants|
			wants.js
		end		
	end

	def leido		
		@comment = Comment.find(params[:id])
		respond_to do |wants|
			if @comment.update_attributes(leido: true)					
				wants.js 			
			else
				render mensajes_path
			end
		end
		
	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	def create
		@contact = Contact.create(params[:contact])
		if @contact.save
			flash[:success] = "Message sent..."
			redirect_to root_path
		else
			flash[:error] = "Message failed"
			redirect_to root_path
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_filter :loguear_user, except:[:index, :show]
	
	def index
		@posts = Post.paginate(:page => params[:page], :per_page => 6).order('created_at DESC')
		respond_to do |format|
	      format.html # index.html.erb
	      format.json { render json: @products }
	    end
	end

	def new
		@post = Post.new
	end

	def create		
		@post = current_user.posts.create(params[:post])
		if @post && @post.save
			flash[:notice] = "Post creado"
			redirect_to post_title_path(@post.title)
		else			
			render 'new'			
		end
	end

	def show		
		@post = Post.find_by_title(params[:title])				
		if @post
			@otros = Post.otros(@post)
			@comment = @post.comments.build
			render 'show'		
		else
			flash[:error] = "Post no encontrado"
			redirect_to root_path
		end		
	end

	def edit
		@post = current_user.posts.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		if @post.update_attributes(params[:post])
			flash[:notice] = "Post Updateado correctamente."
			redirect_to post_title_path(@post.title)
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to root_path, notice: "Post borrado."
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:session][:email])
  	if user && user.authenticate(params[:session][:password])
  		log_in user
  		flash[:success] = "Bienvenido #{user.name}"
  		redirect_to root_path
  	else
  		flash[:error] = "Mal passsword"
  		render 'new'
  	end
  end

  def destroy
  	log_out 
  	redirect_to root_path, notice: "Loged Out!"
  	#self.current_user = nil
  	#session[:rakun].delete
  	#redirect_to root_url, flash[:notice] = "Chau!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def mensajes
		store_location
		@noleidos = Comment.paginate(:page => params[:page],
		 :per_page => 10).order('created_at DESC').where('leido = ?', false)
		@leidos = Comment.where('leido = ?',true)
	end
end

app/helpers/application_helper.rb
# encoding: utf-8
module ApplicationHelper
	@@a = 0
	COLORES = ["rojo", "azul", "verde","amarillo_claro"]

	def log_in(user)		
		session[:rakun] = user.email
		current_user = user	
	end

	def loged_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user
	end
	def current_user
		@current_user || User.find_by_email(session[:rakun])
	end

	def log_out
		self.current_user = nil
		session[:rakun] = nil
	end

	def loguear_user
		unless loged_in?
			store_location
			redirect_to entrar_path
		end
	end

	def store_location
		session[:return_to] = request.fullpath
	end

	def donde_ir(post)
		if loged_in?
			mensajes_path
		else
			post_title_path(post.title)
		end
	end
	
	def siguiente(letra, cycle)
		if cycle == "pull-left"			
			"« #{letra.title}"		
		else			
			"#{letra.title} »"
		end		
	end

	def colores
		a = COLORES.first
		COLORES.delete(a)
		COLORES.push(a)
		a
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.haml
- if !comment.created_at.nil?
	%h3#coment_header Comments
	.wraper{id: "grupo_#{comment.id}"}
		.span3.tiempo
			= time_tag comment.created_at.to_date
			- if loged_in?
				%br
				= link_to "Borrar",
				 post_comment_path(comment.post_id,comment.id),
				  method: :delete,remote: true, class: "borrar_link_comment btn btn-inverse btn-small"
		.span7.individual_comentario{id: "comment_#{comment.id}"}
			.head_coment
				%span.contador.pull-right
					\#
					= comment_counter + 1
				%h3			
					= comment.name			
			%p= comment.content			
		

app/views/comments/_comment_form.html.haml
.span7.offset3
  %fieldset#fieldseta
    %legend#legenda Send a comment
    = form_for([@post, @comment]) do |f|				
      = f.label :email
      = f.text_field :email, placeholder: "Email..."
      = f.label :name		
      = f.text_field :name, placeholder: "Your Name..."
      = f.label :content,"Comment"
      = f.text_area :content, placeholder: "Your Comment..."
      .action
        = f.submit "Enviar", class: "btn btn-inverse"

app/views/comments/destroy.js.erb
$('#grupo_<%= escape_javascript(@id.to_s)%>').slideUp('slow',function() {	
	$(this).remove()
})
$('#mensaje_cuenta').fadeToggle(500,'linear',function() {
	$(this).text('<%= escape_javascript(@noleidos.count.to_s)%>')
	$(this).fadeToggle()
})

app/views/comments/leido.js.erb
$('#grupo_<%= escape_javascript(@comment.id.to_s)%>').slideUp('slow',function() {	
	$(this).remove()
})
$('#mensaje_cuenta').fadeToggle(500,'linear',function() {
	$(this).text('<%= escape_javascript(@noleidos.count.to_s)%>')
	$(this).fadeToggle()
})

app/views/contactmail/enviar_email.html.erb
Hola Daniel, te mandaron un info de contacto en tu blog
	
		<h3><%= @contact.name %></h3>
	<p>EMAIL: </b><%= @contact.email %></b></p>
	
	<p><%= @contact.msg %></p> 

Entrar a tu blog: <%= entrar_url %>

app/views/layouts/_derecha.html.haml
= link_to root_path, id: "a_home" do
	%b.icon-home.icon-white
	Home
%h4 Latest Posts
%ul.ul_derecha
	- @ultimos.each do |post|
		%li.li_derecha= link_to post.title, post_title_path(post.title)
	

app/views/layouts/_footer.html.haml
.pull-right= link_to "Hide", '#', id: "hide_contact"
%ul
	%li			
		= link_to "Contact me", '#', id: "contact_link"			
		= form_for @contact,method: :post, html:{class: "contact_form"} do |f|
			= f.label :name
			= f.text_field :name, placeholder: "Your Name...",id: "contact_name"
			= f.label :email
			= f.text_field :email, placeholder: "Your Email...",id: "contact_email"
			= f.label :msg, "Message"
			= f.text_area :msg,placeholder: "Your message...",id: "contact_msg"
			= f.submit "Send", class: "btn btn-primary btn-inverse"

app/views/layouts/_header.html.haml
.navbar.navbar-inverse.navbar-fixed-top
	.navbar-inner
		.container
			%a.btn.btn-navbar{:href => '#',data: {"toggle" => "collapse", "target"=> ".nav-collapse"}}
				%span.icon-bar
				%span.icon-bar
				%span.icon-bar
			= link_to "Rakun Blog!", root_path, class: "brand"
			.nav-collapse.collpase
			%ul.nav.pull-right#top_bar
				- if @noleidos.count != 0
					%li
						= link_to mensajes_path do 						
							%span.badge.badge-success#mensaje_cuenta
								= @noleidos.count
							Nuevos Mensajes
				%li= link_to "Crear post", new_post_path
				- if @post && @post.title
					%li= link_to "Editar Post", edit_post_path(@post)
					%li= link_to "Borrar Post", post_path(@post),confirm: "Borrar post?", method: :delete
				%li= link_to "Log out", salir_path, method: :delete

			

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>  
</head>
<body>
	<% if loged_in? %>
		<%= render 'layouts/header' %>
	<% end %>
	<div class="page-header">	
		<%= image_tag ("rails.png") %>	
		<h1>Ruby on Rails Dev.</h1>
	</div>
<div class="row">
	<% flash.each do |key, value|%>
    	<div class="span6 offset5 alert alert-<%= key%>"><%= value %></div>
	<% end %>
</div>
<div class="row">	
	<div class="cont span10 offset3">
		<%= yield %>		
	</div>
	<nav class="span4">
		<%= render 'layouts/derecha' %>
	</nav>
</div>
<footer id="foot">
	<%= render 'layouts/footer' %>
</footer>
</body>
</html>

app/views/posts/_form.html.haml
.row 
  .span9.form_centrado
    %fieldset#fieldseta.post
      %legend#legenda Crea un post
      = form_for @post do |f|    
        = f.label :title, "Titulo"
        = f.text_field :title, placeholder: "Escrive un titulo"
        = f.label :content, "Contenido"
        = f.text_area :content, placeholder: "Contenido del post..."
        .action
          = f.submit "Crear Post!", id: "sub_form", class: "btn-inverse"
      
  

app/views/posts/_post.html.haml
- @title = "Blog Index"
%article{class: colores}
  %header          
    = link_to post_title_path(post.title) do        
      = post.title
  .izquierda.pull-left
    %b.icon-white.icon-time
    = time_tag post.created_at.to_date
  %div.derecha       
    %p      
      = pluralize post.comments.count, "comment"
      %b.icon-white.icon-comment      
  .content.formato
    = truncate_html post.content
    = link_to 'Read More', post_title_path(post.title)

app/views/posts/_single_post.html.haml
- @title = @post.title
%header.show_post_header
	%h1        
		= @post.title      
.izquierda.pull-left
	%b.icon-white.icon-time
	= time_tag @post.created_at.to_date
%div.derecha
	= pluralize @post.comments.count, "Comment"
	%b.icon-white.icon-comment    
.content.show_post_content.formato= RedCloth.new(@post.content).html_safe

app/views/posts/edit.html.haml
= render 'form'

app/views/posts/index.html.haml
= will_paginate @posts
= render @posts
= will_paginate @posts

app/views/posts/new.html.haml
= render 'form'

app/views/posts/show.html.haml
%article(class= colores)
	.paginacion				
		-@otros.each do |i|
			- cycle("pull-left", "pull-right")
			- if !i.empty?
				= content_tag(:a,siguiente(i.first, current_cycle), {href: i.first.title, class: current_cycle })
	= render 'single_post'
	%section.row.comments		
		= render @post.comments
	%section.row.comment_form
		= render 'comments/comment_form'

app/views/usermail/borrar_comentario.html.erb
<h3>Hola <b><%= @name %></b>.</h3>
	<h4>Este mensaje es para decirte que borre tu comentario.</h4>

Tu Commentario era:
	<code><%= @content %></code>
		

Saludos, Rakun~

app/views/usermail/borrar_comentario.text.erb
Hola <%= @comment.name %>.
	Este mensaje es para decirte que borre tu comentario.

Tu Commentario era:
	<%= @comment.content %>
		<%= @comment.created_at %>

Saludos, Rakun~

app/views/usermail/comentario_creado.html.erb
Daniel tenes un nuevo comentario en tu blog:

<h3>De: <%= @comment.email %></h3>	
<h3><%= @comment.name %></h3>
	<p><%= @comment.content %></p>

	<%= time_tag @comment.created_at.to_date %>

app/views/users/mensajes.html.haml
.row.mensaje
	= will_paginate @noleidos
	- @noleidos.each do |f|
		.gruaper{class: colores, id: "grupo_#{f.id}"}
			.span4.mensajes_izquierda
				%ul
					%li					
						= f.name
					%li 
						= f.email
				= link_to "Borrar",
				  post_comment_path(f.post_id,f.id),remote: :true,
				  method: :delete,confirm: "Borrar comentario?",
				  class: "borrar_link_comment btn btn-inverse btn-small"
				= link_to "Ver Post",
				  post_title_path(f.post.title,anchor: "coment_header"),
				  class: "borrar_link_comment btn btn-inverse btn-small"
				%br
				= link_to "Marcar como leido", comment_leido_path(f.id),
				  class: "borrar_link_comment btn btn-inverse btn-small",
				  method: :put, remote: :true,confirm: "Marcar comentario como leido?"
			.span6.single_mensaje
				%p= f.content
	= will_paginate @noleidos, class: "pagination margin_top"